import React, { useContext, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { App_Feature } from "../utils/data"
import {
  LuSparkles,
  LuChevronDown,
  LuChevronUp,
  LuArrowRight,
  LuMenu,
  LuX,
  LuUser,
  LuClock,
  LuPen,
  LuCircleHelp,
  LuBookmark,
  LuCpu,
  LuCircleCheck,
  LuStar,
  LuBookOpen
} from 'react-icons/lu'
import Modal from '../components/Modal'
import Login from './Auth/Login'
import Signup from './Auth/Signup'
import { UserContext } from '../context/userContext'
import ProfileInfoCard from '../components/Cards/ProfileInfoCard'

const LandingPage = () => {
  const { user } = useContext(UserContext)
  const navigate = useNavigate();
  const [openAuthModel, setopenAuthModel] = useState(false);
  const [currentPage, setcurrentPage] = useState("login");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [activeFaq, setActiveFaq] = useState(null);

  const handleCTA = () => {
    if (!user) {
      setcurrentPage("signup");
      setopenAuthModel(true);
    } else {
      navigate("/dashboard");
    }
  };

  const getIcon = (index) => {
    switch (index) {
      case 0: return <LuUser className="w-5 h-5 text-[#FF9324] group-hover:text-white transition-colors" />;
      case 1: return <LuClock className="w-5 h-5 text-[#FF9324] group-hover:text-white transition-colors" />;
      case 2: return <LuPen className="w-5 h-5 text-[#FF9324] group-hover:text-white transition-colors" />;
      case 3: return <LuCircleHelp className="w-5 h-5 text-[#FF9324] group-hover:text-white transition-colors" />;
      case 4: return <LuBookmark className="w-5 h-5 text-[#FF9324] group-hover:text-white transition-colors" />;
      default: return <LuSparkles className="w-5 h-5 text-[#FF9324] group-hover:text-white transition-colors" />;
    }
  };

  const faqItems = [
    {
      q: "How does InterviewEdge generate interview questions?",
      a: "InterviewEdge uses your selected role, experience level, topics, and job requirements to generate personalized interview questions that match your target position and skill level."
    },
    {
      q: "Are the answers generated by AI?",
      a: "Yes. Every question comes with an AI-generated sample answer designed to help you understand what interviewers expect and how to structure your response effectively."
    },
    {
      q: "What does the 'Learn More' feature do?",
      a: "The Learn More feature provides detailed explanations, concept breakdowns, best practices, and real-world examples to help you fully understand the topic behind each question."
    },
    {
      q: "Can I customize the topics for question generation?",
      a: "Absolutely. You can specify technologies, concepts, frameworks, or interview areas you want to focus on, and InterviewEdge will tailor the generated content accordingly."
    }
  ];

  return (
    <>
      <div className='w-full min-h-screen bg-[#FAF9F6] text-stone-900 font-sans antialiased selection:bg-orange-100 selection:text-orange-950 relative overflow-x-hidden'>

        {/* Dynamic Glowing Blobs for Premium Visual Depth */}
        <div className="absolute top-[8%] -left-48 w-96 h-96 bg-orange-200/20 rounded-full blur-3xl animate-blob1 pointer-events-none" />
        <div className="absolute top-[35%] -right-48 w-96 h-96 bg-indigo-100/20 rounded-full blur-3xl animate-blob2 pointer-events-none" />
        <div className="absolute top-[70%] left-1/4 w-[600px] h-[600px] bg-orange-100/15 rounded-full blur-3xl animate-blob3 pointer-events-none" />

        {/* Header Navigation */}
        <header className='w-full pt-4 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto sticky top-0 z-50 transition-all duration-300'>
          <div className='w-full backdrop-blur-md  h-20 flex justify-between items-center px-6 sm:px-8'>
            <div
              className='text-lg sm:text-xl font-extrabold tracking-tight text-stone-950 flex items-center gap-1.5 cursor-pointer select-none'
              onClick={() => navigate("/")}
            >
              InterviewEdge<span className="text-[#FF9324] font-black">.</span>
            </div>

            <div className='hidden md:flex items-center gap-4 relative z-10'>
              {user ? (
                <ProfileInfoCard />
              ) : (
                <>

                  <button
                    className='bg-stone-950 text-stone-50 text-sm font-semibold px-6 py-2.5 rounded-xl hover:bg-[#FF9324] transition-all duration-300 cursor-pointer shadow-md hover:shadow-orange-200'
                    onClick={() => { setopenAuthModel(true); setcurrentPage("login"); }}
                  >
                    Login
                  </button>
                </>
              )}
            </div>

            {/* Mobile Menu Toggle Button */}
            <div className="flex md:hidden items-center">
              <button
                onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                className="text-stone-950 hover:text-[#FF9324] transition-colors p-2 cursor-pointer"
                aria-label="Toggle Menu"
              >
                {mobileMenuOpen ? <LuX className="w-6 h-6" /> : <LuMenu className="w-6 h-6" />}
              </button>
            </div>
          </div>

          {/* Mobile Dropdown Panel */}
          {mobileMenuOpen && (
            <div className="md:hidden mt-2 rounded-2xl border border-stone-200/40 bg-white/95 backdrop-blur-md px-6 py-6 flex flex-col gap-4 shadow-xl animate-fadeIn">
              <div className="pt-2 flex flex-col gap-3">
                {user ? (
                  <ProfileInfoCard />
                ) : (
                  <>
                    <button
                      className='w-full text-stone-800 text-sm font-semibold py-3 text-center border border-stone-200 rounded-xl hover:bg-stone-50 transition-all cursor-pointer'
                      onClick={() => {
                        setMobileMenuOpen(false);
                        setopenAuthModel(true);
                        setcurrentPage("login");
                      }}
                    >
                      Login
                    </button>
                    <button
                      className='w-full bg-[#FF9324] text-white text-sm font-semibold py-3 rounded-xl hover:bg-stone-900 transition-all cursor-pointer text-center'
                      onClick={() => {
                        setMobileMenuOpen(false);
                        setopenAuthModel(true);
                        setcurrentPage("signup");
                      }}
                    >
                      Signup Free
                    </button>
                  </>
                )}
              </div>
            </div>
          )}
        </header>

        {/* Hero Section */}
        <main className='container mx-auto px-4 sm:px-6 lg:px-8 pt-12 pb-24 max-w-7xl relative z-10'>

          <div className='grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-center mb-20 lg:mb-28'>
            {/* Left Frame: Premium Typography copy */}
            <div className='lg:col-span-6 flex flex-col items-start text-left'>

              {/* Elegant Micro Badge */}
              <div className='inline-flex items-center gap-2 text-[10px] sm:text-[11px] font-bold tracking-[0.12em] uppercase text-orange-700 bg-orange-100/60 px-3.5 py-1.5 rounded-full border border-orange-200/50 mb-6 animate-pulse'>
                <LuSparkles className="text-[#FF9324] w-3.5 h-3.5" /> Intelligent Interview Coaching
              </div>

              <h1 className='text-4xl sm:text-5xl lg:text-6xl font-black text-stone-950 tracking-tight mb-6 leading-[1.08]'>
                A refined approach to mastering your{' '}
                <span className='bg-gradient-to-r from-[#FF9324] to-amber-500 bg-clip-text text-transparent block'>
                  technical execution.
                </span>
              </h1>

              <p className='text-base sm:text-lg text-stone-600 mb-8 leading-relaxed max-w-xl font-light'>
                Cultivating excellence with structured role-specific frameworks, focused deep-dives, and personalized organization. Handcrafted mock interview preparation designed to elevate your professional trajectory.
              </p>

              {/* CTA Action buttons */}
              <div className="w-full sm:flex sm:items-center gap-4">
                <button
                  className='w-full sm:w-auto bg-stone-950 text-stone-50 text-xs sm:text-sm font-semibold tracking-wide px-8 py-4 rounded-xl hover:bg-[#FF9324] hover:shadow-xl hover:shadow-orange-200 transition-all duration-300 cursor-pointer shadow-md active:scale-[0.98] flex items-center justify-center gap-2'
                  onClick={handleCTA}
                >
                  Get Started <LuArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Right Frame: Split Mockup (Code Editor + AI Assessment Dashboard) */}
            <div className='lg:col-span-6 w-full flex justify-center'>
              <div className='relative w-full max-w-[580px] lg:max-w-none'>
                {/* Glow behind frame */}
                <div className="absolute -inset-1.5 rounded-3xl" />

                {/* Browser Container Frame */}
                <div className='p-3 bg-white rounded-3xl border border-stone-200/80 shadow-2xl w-full'>

                  {/* Browser Chrome Header bar */}
                  <div className="flex items-center justify-between px-3 py-2 bg-stone-50 rounded-t-2xl border-b border-stone-100/80 mb-3">
                    <div className="flex items-center gap-1.5">
                      <span className="w-2.5 h-2.5 rounded-full bg-red-400" />
                      <span className="w-2.5 h-2.5 rounded-full bg-yellow-400" />
                      <span className="w-2.5 h-2.5 rounded-full bg-green-400" />
                    </div>
                    <div className="w-44 sm:w-52 h-5 rounded bg-stone-200/40 flex items-center justify-center text-[9px] text-stone-400 font-mono tracking-wider truncate">
                      interviewedge.com/dashboard/app
                    </div>
                    <div className="w-4" />
                  </div>

                  {/* HTML/CSS Mock Split Dashboard */}
                  <div className="grid grid-cols-1 sm:grid-cols-12 gap-3 bg-stone-950 p-3 rounded-2xl overflow-hidden font-mono min-h-[340px]">

                    {/* Left Panel: Code Terminal (7 cols) */}
                    <div className="sm:col-span-7 bg-stone-900 rounded-xl p-4 border border-stone-800 text-[10px] sm:text-xs flex flex-col justify-between text-stone-300">
                      <div>
                        <div className="flex justify-between items-center text-stone-500 pb-2 border-b border-stone-800/60 mb-3">
                          <span>📄 mock_session.js</span>
                          <span className="text-emerald-500">● Live</span>
                        </div>
                        <p className="text-[#FF9324] font-bold">// Setup prep parameters</p>
                        <p className="mt-1 text-slate-400"><span className="text-indigo-400">const</span> edge = <span className="text-indigo-400">new</span> InterviewEdge({"{"}</p>
                        <p className="pl-4 text-emerald-400">role: <span className="text-stone-300">"Senior Frontend"</span>,</p>
                        <p className="pl-4 text-emerald-400">focus: <span className="text-stone-300">["React Lifecycles"]</span></p>
                        <p className="text-slate-400">{"}"});</p>
                        <p className="mt-2 text-slate-400"><span className="text-indigo-400">await</span> edge.generateFeedback(answers);</p>
                      </div>
                      <div className="bg-stone-950/80 p-2.5 rounded border border-stone-800/80 mt-4 text-[9px] text-stone-400 font-sans">
                        ⚡ Press <kbd className="bg-stone-800 px-1 rounded text-stone-200">Cmd + Enter</kbd> to submit response.
                      </div>
                    </div>

                    {/* Right Panel: AI Response HUD (5 cols) */}
                    <div className="sm:col-span-5 bg-stone-900/60 rounded-xl p-4 border border-stone-800/80 flex flex-col justify-between">
                      <div className="flex flex-col gap-3.5">
                        <div className="flex items-center gap-1.5 text-stone-400 text-[9px] uppercase font-bold tracking-wider">
                          <LuCpu className="w-3.5 h-3.5 text-[#FF9324]" /> AI Analysis
                        </div>

                        {/* Score Circle */}
                        <div className="flex items-center gap-3 bg-stone-950 p-2.5 rounded-lg border border-stone-800/60">
                          <div className="w-9 h-9 rounded-full bg-emerald-500/10 border-2 border-emerald-500 flex items-center justify-center text-emerald-400 text-xs font-bold">
                            92%
                          </div>
                          <div>
                            <div className="text-[10px] font-bold text-stone-200 font-sans leading-none">Concept Match</div>
                            <div className="text-[8px] text-stone-500 font-mono mt-0.5">Hydration lifespan</div>
                          </div>
                        </div>

                        {/* Analysis notes */}
                        <p className="text-[10px] text-stone-400 leading-relaxed font-sans font-light">
                          "Accurate breakdown of render lifecycles. Expand on state reconciliation for max grade."
                        </p>
                      </div>

                      {/* Small badge list */}
                      <div className="flex flex-wrap gap-1 mt-4">
                        <span className="text-[8px] text-indigo-400 bg-indigo-950 border border-indigo-900 px-1.5 py-0.5 rounded font-mono">#React</span>
                        <span className="text-[8px] text-amber-400 bg-amber-950 border border-amber-900 px-1.5 py-0.5 rounded font-mono">#VirtualDOM</span>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>



          {/* How It Works Journey Section */}
          <section id="how-it-works" className="py-16 border-t border-stone-200/50 scroll-mt-24">
            <div className="text-center mb-16 max-w-xl mx-auto">
              <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#FF9324] mb-3">Workflow</h2>
              <p className="text-2xl sm:text-3xl lg:text-4xl font-extrabold tracking-tight text-stone-955">How InterviewEdge works</p>
              <p className="text-sm text-stone-500 mt-3 font-light leading-relaxed">Three simple steps to align your technical preparation and ace your loop panels.</p>
            </div>

            {/* Stepper Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
              {[
                {
                  step: "01",
                  title: "Choose Your Role & Experience Level",
                  desc: "Enter your target role, years of experience, interview topics, and any specific requirements. InterviewEdge uses your inputs to create a personalized question bank tailored to your preparation needs.",
                  icon: <LuUser className="w-5 h-5 text-stone-950" />
                },
                {
                  step: "02",
                  title: "AI-Curated Interview Preparation",
                  desc: "Receive role-specific interview questions along with well-structured sample answers. Practice important concepts, review expected responses, and understand what interviewers look for in strong candidates.",
                  icon: <LuPen className="w-5 h-5 text-stone-950" />
                },
                {
                  step: "03",
                  title: "Unlock Detailed AI Explanations",
                  desc: "Need more clarity? Click 'Learn More' on any question to access detailed explanations, underlying concepts, best practices, and real-world context. Go beyond memorizing answers and build true interview confidence.",
                  icon: <LuCpu className="w-5 h-5 text-stone-950" />
                }
              ].map((item, idx) => (
                <div key={idx} className="relative flex flex-col items-center md:items-start text-center md:text-left bg-white p-8 rounded-2xl border border-stone-200/40 shadow-[0_4px_20px_rgba(0,0,0,0.01)] hover:shadow-[0_8px_25px_rgba(0,0,0,0.02)] transition-shadow">
                  <div className="absolute -top-5 left-8 md:left-6 w-10 h-10 rounded-xl bg-[#FF9324] text-white flex items-center justify-center font-bold text-sm shadow-md shadow-orange-200">
                    {item.step}
                  </div>
                  <div className="p-3 bg-stone-100 rounded-xl w-fit mb-5 mt-3">
                    {item.icon}
                  </div>
                  <h3 className="text-base font-bold text-stone-955 tracking-tight mb-2">{item.title}</h3>
                  <p className="text-xs sm:text-sm text-stone-500 leading-relaxed font-light">{item.desc}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Features Grid Showcase */}
          <section id="features" className='py-20 border-t border-stone-200/50 scroll-mt-24'>
            <div className='text-center mb-16 max-w-xl mx-auto'>
              <h2 className='text-xs font-bold tracking-[0.2em] uppercase text-[#FF9324] mb-3'>
                The Platform
              </h2>
              <p className='text-2xl sm:text-3xl lg:text-4xl font-extrabold tracking-tight text-stone-955'>
                Everything you need to align your tactical delivery.
              </p>
            </div>

            {/* Grid displaying all 5 modules from App_Feature */}
            <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-6'>
              {App_Feature.map((feature, index) => (
                <div
                  className='group relative bg-white p-6 rounded-2xl border border-stone-200/60 shadow-[0_4px_25px_rgba(0,0,0,0.01)] hover:border-orange-300 hover:shadow-[0_12px_30px_rgba(255,147,36,0.04)] hover:-translate-y-0.5 transition-all duration-300 flex flex-col justify-between min-h-[230px]'
                  key={feature.id || index}
                >
                  <div>
                    <span className="absolute top-6 right-6 text-[10px] font-mono text-stone-300 group-hover:text-[#FF9324] font-semibold tracking-widest transition-colors">// 0{index + 1}</span>

                    {/* Icon container */}
                    <div className="w-10 h-10 rounded-xl bg-orange-55 border border-orange-100 flex items-center justify-center mb-5 group-hover:bg-[#FF9324] transition-all duration-300">
                      {getIcon(index)}
                    </div>
                    <h3 className='text-base font-bold text-stone-950 tracking-tight mb-2 group-hover:text-[#FF9324] transition-colors'>
                      {feature.title}
                    </h3>
                    <p className='text-slate-500 text-xs sm:text-[13px] leading-relaxed font-normal'>
                      {feature.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </section>


          {/* Interactive FAQ Accordion Layout */}
          <section id="faq" className="py-20 border-t border-stone-200/50 scroll-mt-24">
            <div className="text-center mb-16 max-w-xl mx-auto">
              <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#FF9324] mb-3">FAQ</h2>
              <p className="text-2xl sm:text-3xl lg:text-4xl font-extrabold tracking-tight text-stone-955">Common questions answered</p>
            </div>

            <div className="max-w-2xl mx-auto flex flex-col gap-4">
              {faqItems.map((item, idx) => {
                const isOpen = activeFaq === idx;
                return (
                  <div
                    key={idx}
                    className="bg-white rounded-2xl border border-stone-200/60 overflow-hidden transition-all duration-300"
                  >
                    <button
                      onClick={() => setActiveFaq(isOpen ? null : idx)}
                      className="w-full flex items-center justify-between p-5 text-left text-xs sm:text-sm font-bold text-stone-955 hover:bg-stone-50 transition-colors cursor-pointer"
                    >
                      <span>{item.q}</span>
                      {isOpen ? (
                        <LuChevronUp className="w-4.5 h-4.5 text-[#FF9324] transition-transform" />
                      ) : (
                        <LuChevronDown className="w-4.5 h-4.5 text-stone-400 transition-transform" />
                      )}
                    </button>
                    {isOpen && (
                      <div className="px-5 pb-5 pt-1 text-xs sm:text-sm text-stone-500 font-light leading-relaxed animate-slideDown">
                        {item.a}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </section>
        </main>

        {/* Upgrade Footer Area */}
        <footer className='border-t border-stone-200/80 bg-white py-6 px-4 md:px-8 relative z-10'>
          <div className="container mx-auto max-w-6xl border-t border-stone-100 flex flex-col sm:flex-row justify-between items-center gap-4 text-[10px] text-stone-400 tracking-[0.1em] uppercase font-semibold">
            <div>
              &copy; {new Date().getFullYear()} InterviewEdge. All rights reserved.
            </div>
            <div>
              Made With Love &bull; Happy Coding
            </div>
          </div>
        </footer>
      </div>

      {/* Modal Authentication Interface Wrapper */}
      <Modal
        isOpen={openAuthModel}
        onClose={() => {
          setopenAuthModel(false);
          setcurrentPage('login');
        }}
        hideHeader
      >
        <div className="p-3 bg-white text-stone-900 rounded-sm">
          {currentPage === 'login' && (<Login setcurrentPage={setcurrentPage} onClose={() => { setopenAuthModel(false); setcurrentPage('login'); }} />)}
          {currentPage === 'signup' && (<Signup setcurrentPage={setcurrentPage} onClose={() => { setopenAuthModel(false); setcurrentPage('login'); }} />)}
        </div>
      </Modal>
    </>
  )
}

export default LandingPage